sudo: required
services:
  - docker

before_install:
  - docker build -t markjhollands/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run markjhollands/react-test npm test -- --coverage

after_success:
  - docker build -t markjhollands/multi-client ./client
  - docker build -t markjhollands/multi-nginx ./nginx
  - docker build -t markjhollands/multi-server ./server
  - docker build -t markjhollands/multi-worker ./worker